#!/bin/sh
# Autostart file for penguinRice

# Wallpaper
~/.fehbg &

# Bar
~/.config/polybar/launch.sh &

# Compositor
picom --config ~/.config/picom/picom.conf &

# System tray
nm-applet &
blueberry-tray &

# Enable numlock
numlockx on &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Notification
dunst --config ~/.config/dunst/dunstrc &

# Power manager daemon
xfce4-power-manager --daemon &

# Autolock
xss-lock -- betterlockscreen -l &

# Ibus daemon
ibus-daemon -drx &

# Other
xsetroot -cursor_name left_ptr
libinput-gestures-setup start
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0
