#! /bin/sh
# penguinRice (TokyoNight)

# Start sxhkd
sxhkd &

# Workspaces
workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6'
		( (name++))
	done
}

workspaces

# bspwm config
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc rule -a URxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset
bspc config border_width 0
bspc config border_radius 10
bspc config window_gap 10
bspc config focus_follows_pointer true
bspc config split_ratio 0.51
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focused_border_color \#a9b1d6
bspc config normal_border_color \#1a1b26

# Autostart
~/.config/bspwm/autostart

# Generate lockscreen wallpaper
betterlockscreen -u ~/wallpapers/tokyonight/tokyonight.png

export _JAVA_AWT_WM_NONREPARENTING=1
