#! /bin/sh

sxhkd &

workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6'
		( (name++))
	done
}

workspaces

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc rule -a URxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset
bspc config border_width 0
bspc config border_radius 10
bspc config window_gap 10
bspc config focus_follows_pointer true
bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config normal_border_color "#44475a"
bspc config focused_border_color "#bd93f9"

feh --bg-fill ~/wallpapers/dracula/dracula.png

xrdb -load ~/.Xresources

~/.config/polybar/launch.sh

xsetroot -cursor_name left_ptr

betterlockscreen -u ~/wallpapers/dracula/dracula.png

picom --config ~/.config/picom/picom.conf &
sleep 2

nm-applet &

numlockx on &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xset s 480 dpms 600 600 600 &

dunst --config ~/.config/dunst/dunstrc &

~/.config/bspwm/scripts/low_bat_notifier.sh

blueberry-tray &

xfce4-power-manager --daemon &

xss-lock -- betterlockscreen -l &

ibus-daemon -drx &

libinput-gestures-setup start
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0

export _JAVA_AWT_WM_NONREPARENTING=1
