#!/usr/bin/env bash

for archivos in ~/.config/style_folder/catppuccin-macchiato/config/*; do
	cp -R "${archivos}" ~/.config/
done

cp -f "$HOME"/.config/style_folder/catppuccin-macchiato/home/.fehbg "$HOME"

chmod -R +x ~/.config
chmod +x ~/.fehbg

bspc wm -r
pkill -USR1 -x sxhkd
